E-Passport/Models/ErrorViewModel.cs
namespace E_Passport.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

E-Passport/Models/Interfaces/IPassportOffice.cs
namespace E_Passport.Models
{
    public interface IPassportOffice
    {
        IEnumerable<PassportOffice> GetAllOfficeDetails();
        PassportOffice Add(PassportOffice passportOffice);
    }
}

E-Passport/Models/Interfaces/IScheduleAppointment.cs
namespace E_Passport.Models
{
    public interface IScheduleAppointment
    {
        ScheduleAppointment Add(ScheduleAppointment appointmentDetails);
        IEnumerable<ScheduleAppointment> GetAllAppointments();
    }
}

E-Passport/Models/InterfacesImplementation/MockPassportOffice.cs
namespace E_Passport.Models
{
    public class MockPassportOffice : IPassportOffice
    {
        private List<PassportOffice> _passportOfficeList;

        public MockPassportOffice()
        {
            _passportOfficeList = new List<PassportOffice>()
            {
                new PassportOffice() {OfficeID=1, OfficeName="PSK Delhi", Jurisdiction="RPO Delhi", Address="MM Towers, Plot No. 8 & 9, Phase IV, Udyog Vihar, Gurgaon", PhoneNumber=1234567890},
                new PassportOffice() {OfficeID=2, OfficeName="PSK Chennai", Jurisdiction="RPO Chennai", Address="Claret Complex, Duraisamy Reddy Street, Tambaram, Chennai", PhoneNumber=1234567890},
                new PassportOffice() {OfficeID=3, OfficeName="PSK Goa", Jurisdiction="RPO Goa", Address="Passport Seva Kendra, Passport Bhavan, EDC Complex, Patto, Panaji", PhoneNumber=1234567890}
            };
        }

        public PassportOffice Add(PassportOffice passportOffice )
        {
            passportOffice.OfficeID = _passportOfficeList.Max(p => p.OfficeID) + 1;
            _passportOfficeList.Add(passportOffice);
            return passportOffice;
        }

        public IEnumerable<PassportOffice> GetAllOfficeDetails()
        {
            return _passportOfficeList;
        }
    }
}

E-Passport/Models/InterfacesImplementation/MockScheduleAppointment.cs
namespace E_Passport.Models
{
    public class MockScheduleAppointment : IScheduleAppointment
    {
        private List<ScheduleAppointment> _scheduleAppointmentList;

        public MockScheduleAppointment()
        {
            _scheduleAppointmentList = new List<ScheduleAppointment>()
            {new ScheduleAppointment() { MonthID=1, MonthName="January", AvailableDays="3, 4, 5", TimeSlots="10-12, 2-4"} };
        }
        public ScheduleAppointment Add(ScheduleAppointment appointmentDetails)
        {
            
            appointmentDetails.MonthID = _scheduleAppointmentList.Max(s => s.MonthID) + 1;
            _scheduleAppointmentList.Add(appointmentDetails);
            return appointmentDetails;
        }

        public IEnumerable<ScheduleAppointment> GetAllAppointments()
        {
            return _scheduleAppointmentList;
        }
    }
}

E-Passport/Models/PassportOffice.cs
using System.ComponentModel.DataAnnotations;

namespace E_Passport.Models
{
    public class PassportOffice
    {
        public int OfficeID { get; set; }
        [Required]
        public string? OfficeName { get; set; }
        [Required]
        public string? Jurisdiction { get; set; }
        [Required]
        public string? Address { get; set; }
        [Required]
        public int PhoneNumber { get; set; }
    }
}

E-Passport/Models/ScheduleAppointment.cs
using System.ComponentModel.DataAnnotations;

namespace E_Passport.Models
{
    public class ScheduleAppointment
    {
        public int MonthID { get; set; }
        [Required]
        public string? MonthName { get; set; }
        [Required]
        public string? AvailableDays { get; set; }
        [Required]
        public string? TimeSlots { get; set; }
    }
}

E-Passport/Controllers/HomeController.cs
using System.Diagnostics;
using E_Passport.Models;
using Microsoft.AspNetCore.Mvc;

namespace E_Passport.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        
        

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

E-Passport/Controllers/PassportOfficeController.cs
using Microsoft.AspNetCore.Mvc;
using E_Passport.Models;
using System.Diagnostics;

namespace E_Passport.Controllers
{
    public class PassportOfficeController : Controller
    {
        private readonly IPassportOffice _passportRepository;

        public PassportOfficeController(IPassportOffice passportOfficeContext)
        {
            _passportRepository = passportOfficeContext;
        }
        public IActionResult Index()
        {
            var model = _passportRepository.GetAllOfficeDetails();
            return View(model);
        }

        [HttpGet]
        public IActionResult AddOffice()
        {

            return View();
        }

        [HttpPost]
        public IActionResult AddOffice(PassportOffice passportOffice)
        {
            if (ModelState.IsValid)
            {
                PassportOffice newOffice = _passportRepository.Add(passportOffice);
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

E-Passport/Controllers/ScheduleAppointmentController.cs
using Microsoft.AspNetCore.Mvc;
using E_Passport.Models;

namespace E_Passport.Controllers
{
    public class ScheduleAppointmentController : Controller
    {
        private readonly IScheduleAppointment _scheduleAppointmentRepository;

        public ScheduleAppointmentController(IScheduleAppointment scheduleAppointmentContext)
        {
            _scheduleAppointmentRepository = scheduleAppointmentContext;
        }
        public IActionResult Index()
        {
            var model = _scheduleAppointmentRepository.GetAllAppointments();
            return View(model);
        }

        [HttpGet]
        public IActionResult AddAppointment()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddAppointment(ScheduleAppointment appointmentDetails)
        {
            if (ModelState.IsValid)
            {
                var newAppointment = _scheduleAppointmentRepository.Add(appointmentDetails);
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

E-Passport/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h3>Welcome to Admin Panel</h3>
<br />
<p>Check Available Passport Offices <a asp-controller="PassportOffice" asp-action="Index">Here</a></p>
<br />
<p>Check Available Appointments <a asp-controller="ScheduleAppointment" asp-action="Index">Here</a></p>

E-Passport/Views/PassportOffice/AddOffice.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model E_Passport.Models.PassportOffice;

@{
    ViewData["Title"] = "Add Office";
}

<div class="row">
    <div class="col-md-4">
        <form asp-controller="PassportOffice" asp-action="AddOffice" method="post">
            <div class="form-group">
                <label asp-for="OfficeName" class="control-label"></label>
                <input asp-for="OfficeName" class="form-control" placeholder="Office Name" />
                <span asp-validation-for="OfficeName" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="Jurisdiction" class="control-label"></label>
                <input asp-for="Jurisdiction" class="form-control" placeholder="Office Name" />
                <span asp-validation-for="Jurisdiction" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" placeholder="Office Name" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" placeholder="Office Name" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Add" class="btn-primary btn" />
            </div>
         </form>
    </div>
</div>

E-Passport/Views/PassportOffice/Index.cshtml
@model IEnumerable<PassportOffice>
@{
    ViewData["Title"] = "Available Offices";
}
<h3>All Passport Office available right now.</h3>
<br />
<hp>Add a Passport Office <a asp-controller="PassportOffice" asp-action="AddOffice">Here</a></hp>
<div>
    <table>
        <tr>
            <th>OfficeID</th>
            <th>OfficeName</th>
            <th>Jurisdiction</th>
            <th>Address</th>
            <th>PhoneNumber</th>
        </tr>
        @foreach(var passportOffice in Model)
        {
            <tr>
                <td>@passportOffice.OfficeID</td>
                <td>@passportOffice.OfficeName</td>
                <td>@passportOffice.Jurisdiction</td>
                <td>@passportOffice.Address</td>
                <td>@passportOffice.PhoneNumber</td>
            </tr>
        }
    </table>
</div>

E-Passport/Views/ScheduleAppointment/AddAppointment.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model ScheduleAppointment; 
@{
    ViewData["Title"] = "Schedule Appointment";
}
<div class="row">
    <div class="col-md-4">
        <form asp-controller="ScheduleAppointment" asp-action="AddAppointment" method="post">
            <div class="form-group">
                <label asp-for="MonthName" class="control-label"></label>
                <input asp-for="MonthName" class="form-control" placeholder="Month name" />
                <span asp-validation-for="MonthName" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="AvailableDays" class="control-label"></label>
                <input asp-for="AvailableDays" class="form-control" placeholder="Available days" />
                <span asp-validation-for="AvailableDays" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="TimeSlots" class="control-label"></label>
                <input asp-for="TimeSlots" class="form-control" placeholder="Time slots" />
                <span asp-validation-for="TimeSlots" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Add Appointment" class="btn-primary btn" />
            </div>
        </form>
    </div>
</div>

E-Passport/Views/ScheduleAppointment/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<ScheduleAppointment>
@{
    ViewData["Title"] = "Available Appointments";
}
<h3>All Passport Office Appointments available right now.</h3>
<br />
<p>Schedule a Appointment <a asp-controller="ScheduleAppointment" asp-action="AddAppointment">Here</a></p>
<div>
    <table>
        <tr>
            <th>MonthID</th>
            <th>MonthName</th>
            <th>AvailableDays</th>
            <th>TimeSlots</th>
        </tr>
        @foreach(var appointment in Model)
        {
            <tr>
                <td>@appointment.MonthID</td>
                <td>@appointment.MonthName</td>
                <td>@appointment.AvailableDays</td>
                <td>@appointment.TimeSlots</td>
            </tr>
        }
    </table>
</div>

E-Passport/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - E_Passport</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/E_Passport.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">E_Passport</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="position:absolute; bottom:1rem; left:1rem">
        <div class="container">
            &copy; 2022 - E_Passport - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>